### ISSUE TITLE
Power loss

### ISSUE THREAD

**Issue by SvMierlo** [TimVosch/Aqua#10]
This will be a quick review on what to do, after a full power loss. Also it will feature how to prevent a power loss from happening.

**Comment by SvMierlo** [comment]
Maybe A bit short don't know what to write more then this. Please help. @TimVosch @roel210 @JarideDooij

**Comment by SvMierlo** [comment]
Will work on this later.

**Comment by TimVosch** [comment]
@roel210 @JarideDooij If someone has some spare time, please take a look at this.
@SvMierlo Please also mention others in the issue when you're having issues with a subject.

**Comment by SvMierlo** [comment]
@TimVosch @roel210 @JarideDooij  It is basically done but could one of you check it, to see if i did the correct thing and if maybe some more needs to be added.
