### ISSUE TITLE
Arduino programming, Logging or uploading to a site?

### ISSUE THREAD

**Issue by SvMierlo** [TimVosch/Aqua#21]
We will need the arduino to save the information we measure and maybe even upload it to a site that makes a graphic of it.

**Comment by TimVosch** [comment]
Yep everything will be sent over the LoRa network to the central server which tracks the data. Atleast an open-source tracking system should be created and if possible graphing, but that could be an external API .

**Comment by TimVosch** [comment]
Assuming this issue can be closed, don't hesitate to reopen.
